fix(quay): Format date, size and Manifest information to be same as on the quay UI
janus-idp/backstage-plugins pull request #101
Opened 2023-02-08 14:35 UTC by fmenesesg

#100

 Format date, size and Manifest information to be same as on the quay UI

2023-02-08 15:49 UTC, tumido requested changes
There seems to be some formatting errors in here. Can you try running `prettier` please?

2023-02-08 16:26 UTC, fmenesesg commented
I execute prettier, now should be ok, can you PTAL

2023-02-09 11:37 UTC, tumido reviewed
LGTM overall, I've left couple of suggestions. Feel free to dismiss them, this is mergeable as is.

2023-02-09 11:37 UTC, tumido commented on plugins/quay/src/components/utils.tsx
> +  return `${Number((sizeInBytes / Math.pow(1024, i)).toFixed(2)) * 1} ${
Hm, can you explain me what is the `* 1` magic about? I'm unable to find a functional difference.

```ts
  return `${Number((sizeInBytes / Math.pow(1024, i)).toFixed(2)) * 1} ${
                                                                 ^^^^
```

2023-02-09 11:37 UTC, tumido commented on plugins/quay/src/components/utils.tsx
> +    ['B', 'kB', 'MB', 'GB', 'TB'][i]
Wouldn't it be better if this array was a global constant? I may be too picky here, just a nit.

2023-02-09 11:37 UTC, tumido commented on plugins/quay/src/components/utils.tsx
> +}
I think a constant would be nice here, but I may be too picky:

```suggestion
export function getSeverityColor(severity: VulnerabilitySeverity) {
export const SEVERITY_COLORS = new Proxy(
  {
    VulnerabilitySeverity.Critical: '#7D1007',
    VulnerabilitySeverity.High: '#C9190B',
    VulnerabilitySeverity.Medium: '#EC7A08',
    VulnerabilitySeverity.Low: '#F0AB00',
    VulnerabilitySeverity.None: '#3E8635'
  },
  {
    get: (o, k) => k in o ? o[k] : '#8A8D90'
  }
)
```

This should be easily addressable via `SEVERITY_COLORS[severity]`.


Again, just a nit, if you don't think agree, feel free to leave as it is, your implementation is completely reasonable and understandable.

2023-02-09 12:11 UTC, tumido approved these changes
After DM discussion the nits are filed as a separate refactor issue. It's minor changes anyways... We can merge this as is. LGTM :+1:

2023-02-09 12:11 UTC, merged