feat: Build Information dialog component to show confirmation or alert
janus-idp/backstage-plugins pull request #1176
Opened 2024-02-06 23:04 UTC by yzhao583

Jira: [https://issues.redhat.com/browse/FLPATH-853](https://issues.redhat.com/browse/FLPATH-853)

Build a information dialog component to ask user to confirm or show alert to user.

![image](https://github.com/janus-idp/backstage-plugins/assets/24922241/d0eb9717-c361-4223-8fb0-c0d197e01f66)
![image](https://github.com/janus-idp/backstage-plugins/assets/24922241/925598a5-c6e9-4e57-ab22-83b8177998fd)

2024-02-07 08:16 UTC, jkilzi requested changes
Looking good!
IMO there is still some room for small improvements. I left some comments in the review on that regard.

2024-02-07 19:34 UTC, yzhao583 commented on plugins/orchestrator/src/components/InfoDialog.stories.tsx
> +      </>
sure

2024-02-07 19:36 UTC, yzhao583 commented on plugins/orchestrator/src/components/InfoDialog.stories.tsx
> +    location data to Google, even when no apps are running.
This is the text copied from an example, but sure.

2024-02-07 19:37 UTC, yzhao583 commented on plugins/orchestrator/src/components/InfoDialog.tsx
> +  close?: () => void;
ok

2024-02-07 19:38 UTC, yzhao583 commented on plugins/orchestrator/src/components/InfoDialog.stories.tsx
> +        close={handleClose}
done

2024-02-07 19:38 UTC, yzhao583 commented on plugins/orchestrator/src/components/InfoDialog.tsx
> +            onClick={close}
done

2024-02-07 19:39 UTC, yzhao583 commented on plugins/orchestrator/src/components/InfoDialog.tsx
> +  const { title, open, close, children, dialogActions } = props;
done

2024-02-07 19:44 UTC, yzhao583 commented
@jkilzi Thanks for the review! Just modified the PR based on feedbacks, please review again, thanks!

2024-02-08 09:02 UTC, jkilzi commented
@yzhao583 PTAL at [this](https://github.com/janus-idp/backstage-plugins/actions/runs/7820291139/job/21334646923?pr=1176#step:3:410).

2024-02-08 15:07 UTC, jkilzi requested changes

2024-02-08 15:07 UTC, jkilzi commented on plugins/orchestrator/package.json
> +    "@storybook/preview-api": "^7.5.3"
Please move it to `devDependency`

2024-02-09 06:23 UTC, jkilzi approved these changes

2024-02-09 06:27 UTC, merged