feat(orchestrator): display a alert dialog when the user fails to abort a running workflow
janus-idp/backstage-plugins pull request #1239
Opened 2024-02-20 20:49 UTC by yzhao583

Jira: [https://issues.redhat.com/browse/FLPATH-995](https://issues.redhat.com/browse/FLPATH-995)

Display a alert dialog when the user fails to abort a running workflow

2024-02-21 08:20 UTC, jkilzi commented on plugins/orchestrator/src/components/WorkflowInstancePage.tsx
> +      Ok
```suggestion
      OK
```

2024-02-21 09:44 UTC, jkilzi requested changes
Just one nit :wink:

2024-02-21 17:21 UTC, yzhao583 commented
@jkilzi Thanks for the review! Committed your suggestion!

2024-02-21 17:37 UTC, caponetto commented on plugins/orchestrator/src/components/WorkflowInstancePage.tsx
> +  message?: string;
Can we make `message` mandatory?

2024-02-21 18:11 UTC, yzhao583 commented on plugins/orchestrator/src/components/WorkflowInstancePage.tsx
> +  message?: string;
Done

2024-02-22 16:08 UTC, caponetto approved these changes

2024-02-22 16:10 UTC, merged