feat(orchestrator): display a description modal before triggering infra-wfs that resulted from an assessment wf
janus-idp/backstage-plugins pull request #1284
Opened 2024-02-27 21:29 UTC by yzhao583

Jira: [https://issues.redhat.com/browse/FLPATH-924](https://issues.redhat.com/browse/FLPATH-924)

Display a description modal before triggering infra-wfs that resulted from an assessment wf

![image](https://github.com/janus-idp/backstage-plugins/assets/24922241/02519150-b3cf-4961-a53b-93b441313c5f)

2024-02-28 08:01 UTC, jkilzi requested changes
PTAL at the comments

2024-02-28 16:25 UTC, yzhao583 commented on plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx
> +        </Box>
@jkilzi This is required by UXD, PTAL at [design](https://www.figma.com/proto/XjdTCb4vDQ7L4Jz1TdHKGq/RHDH---Workflow-Orchestrator?page-id=0%3A1&type=design&node-id=539-1418&viewport=3193%2C-4624%2C0.5&t=OuIn8Kcuq53W4KPT-1&scaling=min-zoom&starting-point-node-id=848%3A1670), if you click the `Move 2 Kube` link, you should be able to see the modal. Thanks

2024-02-28 19:07 UTC, jkilzi commented on plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx
> +        </Box>
ack, I left the same question in the design, let's wait (not too much) for an explanation.
cc @nfarkas

2024-02-28 19:09 UTC, yzhao583 commented on plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx
> +        </Box>
Ok

2024-02-29 14:59 UTC, yzhao583 commented
@jkilzi @nfarkas Can we TAL at this? Thanks

2024-02-29 15:04 UTC, caponetto commented on plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx
> +        </Box>
I'd go with whatever we have on the design and open a new ticket if necessary.

2024-02-29 15:36 UTC, yzhao583 commented on plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx
> +        </Box>
@jkilzi Modified the PR based on the new change from UXD, can you PTAL? thanks

2024-03-03 09:45 UTC, jkilzi approved these changes

2024-03-03 09:48 UTC, merged