Feature/tekton plugin initial code
janus-idp/backstage-plugins pull request #135
Opened 2023-02-17 05:17 UTC by lokeshrangineni

[https://github.com/janus-idp/backstage-plugins/issues/128 - Cecking in the initial Tekton plugin code.

2023-02-17 11:43 UTC, riginoommen requested changes

2023-02-17 11:43 UTC, riginoommen commented on app-config.yaml
> +tekton:
Utilize the env variables for managing configurations like secrets

2023-02-17 11:43 UTC, riginoommen commented on plugins/tekton-pipelines-backend/src/service/pipelinerun.ts
> +  //console.log("Logging the env variable", process.env);
```suggestion
```

2023-02-17 11:43 UTC, riginoommen commented on plugins/tekton-pipelines-backend/src/service/pipelinerun.ts
> +          Authorization: `Bearer ${authorizationBearerToken}`,
Append the ```Bearer``` keyword also in the env variable token

2023-02-17 11:43 UTC, riginoommen commented on plugins/tekton-pipelines-backend/src/service/pipelinerun.ts
> +  console.log("Logging the env variable", process.env.NODE_TLS_REJECT_UNAUTHORIZED);
```suggestion

```

2023-02-17 11:43 UTC, riginoommen commented on plugins/tekton-pipelines-backend/src/service/router.ts
> +    logger.info('PONG!');
```suggestion
```

I think the APi response is sufficient

2023-02-17 11:46 UTC, riginoommen requested changes
I request to lint the code also

2023-02-17 11:46 UTC, riginoommen commented on plugins/tekton-pipelines/src/plugin.ts
> +
unused comments should be removed

2023-02-17 11:49 UTC, riginoommen commented on plugins/tekton-pipelines-backend/src/service/pipelinerun.ts
> +  process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
THis seems not a good idea

2023-02-17 12:02 UTC, tumido requested changes
Hey! Before we even attempt to bring this code in, please collaborate in the discussion on issue #128 to determine the right course of action here.

So far it seems we don't need to bring in anything else than the frontend tekton plugin.

Let's have a clear direction before we rush code in.

2023-02-17 12:10 UTC, lokeshrangineni commented
Hi Tom,

Thank you for the review. I will incorporate your comments. How would you
prefer to have a conversation? Would you like to setup a call? Or I can
ping you as soon as i m back online.

Thanks,
Lokesh

On Fri, Feb 17, 2023 at 7:02 AM Tom Coufal ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey! Before we even attempt to bring this code in, please collaborate in
> the discussion on issue #128
> <https://github.com/janus-idp/backstage-plugins/issues/128> to determine
> the right course of action here.
>
> So far it seems we don't need to bring in anything else than the frontend
> tekton plugin.
>
> Let's have a clear direction before we rush code in.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/janus-idp/backstage-plugins/pull/135#pullrequestreview-1303301049>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEWJLFGUZHIVAGLOTQW32CDWX5SEVANCNFSM6AAAAAAU7AFR4U>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-17 12:14 UTC, tumido commented
Also if you can please come online on Slack for a moment, there's an issue that needs to be addressed asap.

2023-03-21 16:43 UTC, tumido commented
Closing as a result of https://github.com/janus-idp/backstage-plugins/issues/161 discussion.

2023-03-21 16:43 UTC, closed without merging