[WIP] feat: allow user to select repositories from side panel
janus-idp/backstage-plugins pull request #1430
Opened 2024-04-01 22:01 UTC by ciiay

For [RHIDP-1665](https://issues.redhat.com/browse/RHIDP-1665): Allow users to select repositories from organization

Screen recording:

https://github.com/janus-idp/backstage-plugins/assets/26255262/4b9c9204-3b14-4d16-9299-de9ae266510b

2024-04-11 13:48 UTC, invincibleJai commented
https://github.com/janus-idp/backstage-plugins/pull/1357 has been merged now, can do rebase.

2024-04-12 06:33 UTC, debsmita1 commented
A few observations:
- Selected repositories column cannot be sorted
- When selecting repositories from an org, if I uncheck all the selected repos, the "Select" button gets disabled.
- The check icon before "Ready" is missing

2024-04-13 03:04 UTC, ciiay commented
Hi @ShiranHi , @debsmita1 and I have a question about the Ready status of catalog-info.yaml. I have the below two display types and one proposal. If the concept of the proposal makes sense to you, we can also work on a better style of how to display it. Let us know how you think, thank you in advance.

_Type 1_:
Key points: Only show the number of selected repos when part of the repos selected. Always display Check icon for Ready status.
<img width="1247" alt="rhidp_1665_option1" src="https://github.com/janus-idp/backstage-plugins/assets/26255262/7d787c89-6c33-467f-a0c1-90d9395aab21">

_Type 2_:
Key points: Using Check icon as a indicator of All repos of this row are selected. Hide Check icon when part of the repos are selected.
<img width="1247" alt="rhidp_1665_option2" src="https://github.com/janus-idp/backstage-plugins/assets/26255262/942c97af-60ce-4a4a-a05c-708af30b2a90">

_Proposal_:
Key points: Ready status always comes with a Check icon. Using a "/" to show what number out of the total repos are selected. 
<img width="1244" alt="rhidp_1665_option3" src="https://github.com/janus-idp/backstage-plugins/assets/26255262/e5c22559-3dd5-4cd1-9909-160e8df13b3d">

2024-04-14 11:50 UTC, ShiranHi commented
> Hi @ShiranHi , @debsmita1 and I have a question about the Ready status of catalog-info.yaml. I have the below two display types and one proposal. If the concept of the proposal makes sense to you, we can also work on a better style of how to display it. Let us know how you think, thank you in advance.
> 
> _Type 1_: Key points: Only show the number of selected repos when part of the repos selected. Always display Check icon for Ready status. <img alt="rhidp_1665_option1" width="1247" src="https://private-user-images.githubusercontent.com/26255262/322170771-7d787c89-6c33-467f-a0c1-90d9395aab21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTUwOTgsIm5iZiI6MTcxMzA5NDc5OCwicGF0aCI6Ii8yNjI1NTI2Mi8zMjIxNzA3NzEtN2Q3ODdjODktNmMzMy00NjdmLWEwYzEtOTBkOTM5NWFhYjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDExMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZTVhMWE3ZDQ3NDA3ZDljMjE3YzVmOGJlOTI3OGNlM2E3MGM2NmNmM2I0NGVkMzM3NzNmYTkzZmQ1M2FiYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T20bOWYdL-gg5lnEqP5WLTMUbpFeGvi1blugkNdpXSE">
> 
> _Type 2_: Key points: Using Check icon as a indicator of All repos of this row are selected. Hide Check icon when part of the repos are selected. <img alt="rhidp_1665_option2" width="1247" src="https://private-user-images.githubusercontent.com/26255262/322170772-942c97af-60ce-4a4a-a05c-708af30b2a90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTUwOTgsIm5iZiI6MTcxMzA5NDc5OCwicGF0aCI6Ii8yNjI1NTI2Mi8zMjIxNzA3NzItOTQyYzk3YWYtNjBjZS00YTRhLWEwNWMtNzA4YWYzMGIyYTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDExMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMzlkYzc2NTQ3NDlhMDM2OGQ0MWU1OWJlOGU5MzNhNzJkNjI3ZGE0ODNlNGM4ZTg1YjdmYWFhMTViYzU2NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.exft9DzK3_-3D1DmiyALirlz5fvnVLRTThOq5c_LVy8">
> 
> _Proposal_: Key points: Ready status always comes with a Check icon. Using a "/" to show what number out of the total repos are selected. <img alt="rhidp_1665_option3" width="1244" src="https://private-user-images.githubusercontent.com/26255262/322170773-e5c22559-3dd5-4cd1-9909-160e8df13b3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTUwOTgsIm5iZiI6MTcxMzA5NDc5OCwicGF0aCI6Ii8yNjI1NTI2Mi8zMjIxNzA3NzMtZTVjMjI1NTktM2RkNS00Y2QxLTk5MDktMTYwZThkZjEzYjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDExMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1OGI3NDJkNzFkZmQzMDBmMDZkMDZlZWU4MWI2OWYwMjQwYmY4NGM0Y2EzZDUxZGFiNGIyYmJlYTdhNDFjNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pYBq8qFCGE0YjIixSaNZDi20v6jV_7T7ws9H1zZjl6A">

I love this idea, let's write the number of repository selected x/y (for example 3/10). Thank you for bringing this up! 

About the side panel, can we use the basic table style? the rows are too high

2024-04-15 15:13 UTC, debsmita1 requested changes

2024-04-15 15:39 UTC, ciiay commented on plugins/bulk-import/src/components/AddRepositories/AddRepositoriesDrawer.tsx
> +            updateSelectedReposInDrawer={handleCallback}
Good catch. I wanted to use `updateSelectedReposInDrawer` but forgot to update the declaration.

2024-04-15 16:16 UTC, ciiay commented
Hi @debsmita1 Thanks for the review. I updated the PR and the drawer style for a small screen display. Here's the screenshot and it's scrollable too.
<img width="503" alt="rhidp_1665_mobile_view" src="https://github.com/janus-idp/backstage-plugins/assets/26255262/07c18db1-6c54-4127-92a1-4d8ca2966679">

2024-04-16 05:41 UTC, debsmita1 requested changes

2024-04-16 05:41 UTC, debsmita1 commented on plugins/bulk-import/src/components/AddRepositories/AddRepositoriesDrawer.tsx
> +          flexDirection: 'column',
move this to useStyles

2024-04-16 05:41 UTC, debsmita1 commented on plugins/bulk-import/src/utils/repository-utils.tsx
> +  // if (data.repositoryType === 'repository') {
Remove the commented lines

2024-04-16 09:57 UTC, ShiranHi commented
> Hi @ShiranHi I have updated this PR to address the table row height issue. You can confirm the style on the updated screen recording. Thank you.

Looks much better, thank you for this. 
I just saw that the padding between the checkbox and the name is too big, can we reduce it so it will look like in the design ([Figma](https://www.figma.com/file/09Iltd57RiuqOtKWkjy8MH/Bulk-import?type=design&node-id=74%3A10076&mode=design&t=sODyyPnFY9s3WaFK-1))?

<img width="331" alt="image-1" src="https://github.com/janus-idp/backstage-plugins/assets/77277517/30b37c27-79b4-4847-8bf9-22a1198910c8">

2024-04-18 10:37 UTC, debsmita1 requested changes
We do not want to show catalog-info status in the side panel, we want to show it only on the selected repositories table

![Screenshot 2024-04-18 at 4 04 33 PM](https://github.com/janus-idp/backstage-plugins/assets/22490998/c98efd94-56d8-4b40-ab7d-3cfbc53076d9)


Figma:

<img width="835" alt="Screenshot 2024-04-18 at 4 05 08 PM" src="https://github.com/janus-idp/backstage-plugins/assets/22490998/03b11b8d-0de4-4c5e-91c4-7b585c4693f1">

2024-04-18 10:37 UTC, debsmita1 commented on plugins/bulk-import/src/utils/repository-utils.tsx
>            style={{ verticalAlign: 'bottom', paddingTop: '7px' }}
Can you update this to

```suggestion
          style={{ verticalAlign: 'sub', paddingTop: '7px' }}
```

2024-04-18 19:23 UTC, merged