feat(scaffolder): create custom action for adding timestamp to templates
janus-idp/backstage-plugins pull request #1567
Opened 2024-04-26 17:48 UTC by debsmita1

**Resolves:**

https://issues.redhat.com/browse/RHIDP-2192

**Test setup:**

- Follow the README.md to integrate the custom action plugin in the backend.

- Changes in `app-config.yaml`

```
catalog:
  location:
    # Example template
    - type: url
      target: https://github.com/debsmita1/nodejs-ex-1/blob/master/local-template.yaml
      rules:
        - allow: [Template]
```

- Changes in `App.tsx`

```
import {
  CatalogEntityPage,
  CatalogIndexPage,
  CatalogTable,
  CatalogTableRow,
  CatalogTableColumnsFunc,
} from '@backstage/plugin-catalog';

export const AppBase = () => {
  const { AppProvider, AppRouter, dynamicRoutes } =
    useContext(DynamicRootContext);
  const myCustomColumnsFunc: CatalogTableColumnsFunc = entityListContext => {
    if (entityListContext.filters.kind?.value === 'component') {
      return [
        ...CatalogTable.defaultColumnsFunc(entityListContext),
        {
          title: 'Created At',
          ender: (data: CatalogTableRow) =>
            data.entity.metadata.annotations?.['backstage.io/createdAt'],
        },
      ];
    }

    return CatalogTable.defaultColumnsFunc(entityListContext);
  };
  .....
  
  
  <Route
       path="/catalog"
       element={<CatalogIndexPage columns={myCustomColumnsFunc} />}
   />
```

2024-05-01 07:39 UTC, rohitkrai03 reviewed
Overall looks good to me but I am thinking if we really need a custom action for this. Are there plans to use this custom action for other use cases as well?

2024-05-03 12:17 UTC, debsmita1 commented
> Overall looks good to me but I am thinking if we really need a custom action for this. Are there plans to use this custom action for other use cases as well?

@rohitkrai03 updated the PR to create a generic action to annotate objects with labels and annotations. PTAL

2024-05-03 14:21 UTC, Zaperex commented
@debsmita1 I noticed you added a generic custom action for annotating the labels and annotations. I have a similar [custom action](https://github.com/janus-idp/backstage-plugins/pull/1605) in the works that appends a `spec.scaffoldedFrom` field to the `catalog-info.yaml` to enable a custom relation link between software templates and the catalog entities they generated. 

I was wondering if it would be a good idea to extend this generic action to allow modification of the spec field (and potentially other fields in the future). Then we can potentially export and publish both of these `catalog-info.yaml` modification custom actions (timestamping, adding `templatedFrom` field) alongside  the generic custom action as a common package of `catalog-info.yaml` modification custom actions similar to how the [built-in backstage actions](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/createBuiltinActions.ts) are exported rather than having 2 separate custom action packages published?

2024-05-06 09:57 UTC, debsmita1 commented
> @debsmita1 I noticed you added a generic custom action for annotating the labels and annotations. I have a similar [custom action](https://github.com/janus-idp/backstage-plugins/pull/1605) in the works that appends a `spec.scaffoldedFrom` field to the `catalog-info.yaml` to enable a custom relation link between software templates and the catalog entities they generated.
> 
> I was wondering if it would be a good idea to extend this generic action to allow modification of the spec field (and potentially other fields in the future). Then we can potentially export and publish both of these `catalog-info.yaml` modification custom actions (timestamping, adding `spec.templatedFrom` field) alongside this generic custom action as a common package of `catalog-info.yaml` modification custom actions rather than publishing multiple packages for all the future `catalog-info.yaml` modification custom actions. This would be similar to how the [built-in backstage actions](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/createBuiltinActions.ts) are published and exported.
> 
> What are you thoughts?

Absolutely! This totally makes sense. I will update my PR to allow modification in the `spec` field

2024-05-06 20:35 UTC, Zaperex commented
I made a PR (https://github.com/debsmita1/backstage-plugins/pull/3) on your branch with some fixes to the `package.json` exporting to allow it to work in the new backend system. Also fixed up the `yarn lint` issues and the `yarn build` issues so it should pass the tests.

2024-05-07 16:56 UTC, rohitkrai03 requested changes
@debsmita1 Overall looks good. I think it would be beneficial if you could also provide an example template, similar to the one shown here - https://github.com/janus-idp/backstage-plugins/tree/main/plugins/kubernetes-actions/examples/templates.

2024-05-07 16:56 UTC, rohitkrai03 commented on plugins/scaffolder-annotator-action/README.md
> +1. Install the Annotator custom action plugin using the following command:
Maybe add a section on top that explains what this custom action package provides overall? Like all the features and then the specific actions for timestamping and scafolded-from.

2024-05-08 04:43 UTC, ciiay commented
Hi @debsmita1 , I have tried this PR locally and I got "Template action with ID 'catalog:timestamping' is not registered." error. 
<img width="1512" alt="rhidp_2192" src="https://github.com/janus-idp/backstage-plugins/assets/26255262/7bf10312-a953-4ee7-80bf-3bb1506b0aca">
Did I miss anything?

2024-05-08 05:43 UTC, debsmita1 commented
> Hi @debsmita1 , I have tried this PR locally and I got "Template action with ID 'catalog:timestamping' is not registered." error. <img alt="rhidp_2192" width="1512" src="https://private-user-images.githubusercontent.com/26255262/328756624-7bf10312-a953-4ee7-80bf-3bb1506b0aca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNDcwOTIsIm5iZiI6MTcxNTE0Njc5MiwicGF0aCI6Ii8yNjI1NTI2Mi8zMjg3NTY2MjQtN2JmMTAzMTItYTk1My00ZWU3LTgwYmYtM2JiMTUwNmIwYWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA1Mzk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ODQ5ZDZjMjFkZjdkN2ZiMGM4ODU0NTU1MDhmZDU3YWI2NmJiMDczMDIxODQ4OGNhMTVkYTJjNmNhNzY4ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V7WDRcZU-NRcCEUXqV8FBO7hY8gR2R8YSZrpmI_BMTk"> Did I miss anything?

Thanks @ciiay for trying it out. Do you have the new changes in the `scaffolder.ts` file as mentioned in the Readme ?

2024-05-08 16:12 UTC, ciiay commented
Tested in backstage-showcase and it works great 👍 
![image](https://github.com/janus-idp/backstage-plugins/assets/26255262/8763d632-0cb2-436c-84c5-df423bc6d508)

2024-05-09 14:37 UTC, invincibleJai commented
/lgtm

Thanks @debsmita1, this works as described. I tested as static and dynamic way in showcase

2024-05-09 14:41 UTC, merged

2024-05-09 14:45 UTC, hmanwani-rh reviewed
@debsmita1 Added a few comments. Please take a look and let me know if you've any questions.

2024-05-09 14:45 UTC, hmanwani-rh commented on plugins/scaffolder-annotator-action/README.md
> +2. Integrate the custom actions in the `scaffolder-backend` `createRouter` function:
```suggestion
2. Integrate the custom actions in the `scaffolder-backend` `createRouter` function using the following steps:
```

2024-05-09 14:45 UTC, hmanwani-rh commented on plugins/scaffolder-annotator-action/README.md
> +3. To annotate the catalog-info.yaml skeleton with the current timestamp, add the **catalog:timestamping** custom action in your template yaml after the `Fetch Skeleton + Template` step:
```suggestion
3. To annotate the catalog-info.yaml skeleton with the current timestamp, add the `catalog:timestamping` custom action in your template YAML file after the `Fetch Skeleton + Template` step:
```

2024-05-09 14:45 UTC, hmanwani-rh commented on plugins/scaffolder-annotator-action/README.md
> +4. To annotate the catalog-info.yaml skeleton with the template entityRef, add the **catalog:scaffolded-from** custom action in your template yaml after the `Fetch Skeleton + Template` step:
```suggestion
4. To annotate the `catalog-info.yaml` skeleton with the template `entityRef`, add the `catalog:scaffolded-from` custom action in your YAML file after the `Fetch Skeleton + Template` step:
```

2024-05-09 14:45 UTC, hmanwani-rh commented on plugins/scaffolder-annotator-action/README.md
> +To use the `createAnnotatorAction` to create a custom action
```suggestion
You can use the `createAnnotatorAction` to create a custom action using the following parameters:
```

2024-05-09 14:45 UTC, hmanwani-rh commented on plugins/scaffolder-annotator-action/README.md
> +The annotator action accepts the following inputs
```suggestion
The annotator action plugin accepts the following inputs:
```