Audit Log: Track RBAC changes
janus-idp/backstage-plugins pull request #1610
Opened 2024-05-06 02:02 UTC by AndrienkoAleksandr

### What does this pull request do

Implement audit logging for RBAC backend

### Referenced issue:
https://issues.redhat.com/browse/RHIDP-2004

2024-05-06 15:19 UTC, Zaperex requested changes
Upstream backstage is moving towards using their [`LoggerService`](https://github.com/backstage/backstage/blob/4ea48f4e7a9579c3570fe1c560b93a82b5f2f5ae/packages/backend-plugin-api/src/services/definitions/LoggerService.ts#L24) (also refer to the [implementation](https://github.com/backstage/backstage/blob/4ea48f4e7a9579c3570fe1c560b93a82b5f2f5ae/packages/backend-app-api/src/logging/WinstonLogger.ts#L47)) instead of the winston Logger. The `LoggerService` does not contain this `log` function so we should be using the `info` and `error` functions instead to make migration to LoggerService in the future easier.

To get the same behavior as using `log`, you'll need to put the non message fields in the [metadata argument](https://github.com/backstage/backstage/blob/4ea48f4e7a9579c3570fe1c560b93a82b5f2f5ae/packages/backend-app-api/src/logging/WinstonLogger.ts#L172-L182) of the `info` or `error` function. Otherwise, the object containing your audit log message will be logged as an object in the message field. This would result in `[object Object]` being printed if the logger format isn't JSON.

2024-05-06 15:19 UTC, Zaperex commented on plugins/rbac-backend/src/audit-log/audit-logger.ts
> +      message,
```suggestion
```

2024-05-06 15:19 UTC, Zaperex commented on plugins/rbac-backend/src/audit-log/audit-logger.ts
> +    this.logger.error(logMsg);
```suggestion
    const logMsg: LogMsg = {
      isAuditLog: true,
      entityRef,
      source: 'rest',
      modifiedBy,
      time,
    };
    this.logger.error(msg, logMsg);
```

2024-05-06 15:19 UTC, Zaperex commented on plugins/rbac-backend/src/audit-log/audit-logger.ts
> +    this.logger.log(logMsg);
```suggestion
    if (level === 'error'){
      this.logger.error(message, logMsg);
    } else {
      this.logger.info(message, logMsg);
    }
```

2024-05-06 15:19 UTC, Zaperex commented on plugins/rbac-backend/src/audit-log/audit-logger.ts
> +  }
Just sending the `msg` via `logger.error` would result in the entire `LogMsg` object being stuffed into the `message` field of the log. If you want to have the same behavior as `logger.log`, you'll need to provide all the non-message fields of the log in the [`meta` field](https://github.com/backstage/backstage/blob/99305a09da8b0ab628421c66d9d3742cb125362d/packages/backend-plugin-api/src/services/definitions/LoggerService.ts#L25) of the function.

2024-05-07 14:02 UTC, Zaperex commented on plugins/rbac-backend/src/audit-log/audit-logger.ts
> +      `${this.fmtToPastTime(operation)} '${metadata.roleEntityRef}'`
```suggestion
      `${this.fmtToPastTime(operation)} '${metadata.roleEntityRef}'`,
```

2024-05-07 14:03 UTC, Zaperex commented on plugins/rbac-backend/src/audit-log/audit-logger.ts
> +    );
```suggestion
    this.logger.info(
      `${this.fmtToPastTime(operation)} '${metadata.roleEntityRef}'`,
      this.toLogMsgWithRoleInfo(logMsg, metadata)
    );
```

2024-05-20 13:32 UTC, AndrienkoAleksandr commented
close on favour: https://github.com/janus-idp/backstage-plugins/pull/1694

2024-05-20 13:32 UTC, closed without merging