chore(dependencies): Set pluginPackages for all plugins with pluginId
janus-idp/backstage-plugins pull request #1920
Opened 2024-07-22 13:04 UTC by rgolangh

Signed-off-by: Roy Golan <rgolan@redhat.com>

2024-07-22 13:04 UTC, rgolangh commented
@nickboldt please take a look

2024-07-22 13:30 UTC, ydayagi submitted a review, later dismissed

2024-07-22 13:31 UTC, ydayagi commented
/approve

2024-07-22 17:01 UTC, nickboldt commented on plugins/matomo-backend/package.json
> +      "@janus-idp/backstage-plugin-matomo",
so the backend includes the common and front end plugins too?

2024-07-22 17:02 UTC, nickboldt commented on plugins/analytics-module-matomo/package.json
> +      "@janus-idp/backstage-plugin-analytics",
this don't depend on / include the matomo backend and common plugins, only the analytics plugin?

2024-07-22 17:03 UTC, nickboldt commented on plugins/kiali-backend/package.json
> +      "@janus-idp/backstage-plugin-kiali-common",
where does the kiali-common plugin come from?

2024-07-22 17:04 UTC, nickboldt requested changes
can't merge as is, have questions! 

alternative option in https://github.com/janus-idp/backstage-plugins/pull/1921 -- not saying it's better, just simpler.

2024-07-23 06:39 UTC, closed without merging

2024-07-23 06:40 UTC, rgolangh commented
closing in favour of #1921