Custom action to create a SonarQube project
janus-idp/backstage-plugins pull request #206
Opened 2023-03-27 02:57 UTC by jlmayorga

New Backstage [custom action](https://backstage.io/docs/features/software-templates/writing-custom-actions#registering-custom-actions) to create a SonarQube project

Takes care of #177

2023-03-27 15:12 UTC, tumido requested changes
Hey @jlmayorga! Thanks for contributing this! 👍 I have some formalities/nits inline.

2023-03-27 15:12 UTC, tumido commented on plugins/sonarqube-actions/src/actions/index.ts
> +export {createSonarQubeProjectAction} from './createSonarQubeProject'
Missing EOL at EOF

2023-03-27 15:12 UTC, tumido commented on plugins/sonarqube-actions/package.json
> +  "name": "@janus-idp/sonarqube-actions",
```suggestion
  "name": "@janus-idp/backstage-scaffolder-backend-module-sonarqube",
```

Looking at all available scaffolder plugins out there, all use a more descriptive name that contains `scaffolder-backend-module`. Let's follow the conventions, so the module is easier to discover for users.

2023-03-27 20:31 UTC, jlmayorga commented on plugins/sonarqube-actions/src/actions/index.ts
> +export {createSonarQubeProjectAction} from './createSonarQubeProject'
Fixed in c0af8ee

2023-03-31 10:27 UTC, tumido approved these changes
/lgtm
/approve

2023-03-31 10:29 UTC, tumido commented
> Should the plugin directory be renamed as well?

@jlmayorga I don't see a need to rename the folder at this point. We can give the folder structure a redesign/revisit at later point. Right now, I think this is fine, it's understandable for us (me, you, other maintainers). When it becomes a challenge on that front, we may consider renaming it. 🙂

2023-03-31 10:29 UTC, merged