fix(rbac): add more details to unable to create role alert
janus-idp/backstage-plugins pull request #2095
Opened 2024-08-27 10:20 UTC by divyanshiGupta

Fixes: https://issues.redhat.com/browse/RHIDP-3492

<img width="1727" alt="Screenshot 2024-08-27 at 3 49 48 PM" src="https://github.com/user-attachments/assets/854fcfee-14a0-4e98-9246-e74b8a8f49b2">

2024-08-27 13:52 UTC, Zaperex requested changes

2024-08-27 13:52 UTC, Zaperex commented on plugins/rbac/src/components/RolesList/RolesListToolbar.tsx
> +            administrator as you might be conditionally restricted to access the
```suggestion
            administrator as you might be conditionally restricted from accessing the
```

2024-08-28 09:58 UTC, invincibleJai commented
/lgtm

2024-08-28 12:46 UTC, invincibleJai approved these changes

2024-08-28 12:50 UTC, merged