test(ocm-backend): Add development setup using msw handlers
janus-idp/backstage-plugins pull request #230
Opened 2023-04-04 12:44 UTC by SamoKopecky

Add a dedicated development setup for the `ocm-backend` plugin to allow easier development. It is implemented using the `msw` package.

## Additional changes
- Move the fixtures folder since its now used plugin wide instead of just in tests.
- Add a constant of the fixtures location so that if the fixtures are moved again there is only a single change nessescery per file
- Add documentation

In the future we can also use `msw` for test mocking instead of `nock` and use the defined handlers in `handlers.ts`.

2023-04-04 13:00 UTC, tumido requested changes
I love this ❤️  This is great!

I have left a few comments, nits, inline. Otherwise it looks great to me! 👍

2023-04-04 13:00 UTC, tumido commented on plugins/ocm-backend/fixtures/cluster.open-cluster-management.io/managedclusters/cluster1.json
Please also rename the `fixtures` folder to `__fixtures__` so we're using the same naming conventions as topology plugin.

2023-04-04 13:00 UTC, tumido commented on plugins/ocm-backend/fixtures/handlers.ts
> +      );
CAn this also be a fixture?

2023-04-04 13:00 UTC, tumido commented on plugins/ocm-backend/src/helpers/kubernetes.test.ts
> +const fixturesLocation = `${__dirname}/../../fixtures`;
```suggestion
const FIXTURES_DIR = `${__dirname}/../../fixtures`;
```

2023-04-04 13:00 UTC, tumido commented on plugins/ocm-backend/src/helpers/parser.test.ts
> +const fixturesLocation = `${__dirname}/../../fixtures`;
```suggestion
const FIXTURES_DIR = `${__dirname}/../../fixtures`;
```

2023-04-04 13:00 UTC, tumido commented on plugins/ocm-backend/src/service/router.test.ts
> +const fixturesLocation = `${__dirname}/../../fixtures`;
Same as above

2023-04-04 14:16 UTC, SamoKopecky commented on plugins/ocm-backend/src/service/router.test.ts
> +const fixturesLocation = `${__dirname}/../../fixtures`;
Changed in the latest commit.

2023-04-04 14:16 UTC, SamoKopecky commented on plugins/ocm-backend/src/helpers/parser.test.ts
> +const fixturesLocation = `${__dirname}/../../fixtures`;
Changed in the latest commit.

2023-04-04 14:17 UTC, SamoKopecky commented on plugins/ocm-backend/fixtures/handlers.ts
> +      );
Yes it can I added it a fixture.

2023-04-04 14:17 UTC, SamoKopecky commented on plugins/ocm-backend/fixtures/cluster.open-cluster-management.io/managedclusters/cluster1.json
Renamed.

2023-04-05 07:34 UTC, tumido approved these changes
/lgtm
/approve

2023-04-05 07:35 UTC, merged