feat(bulk-import): use react query to fetch repositories
janus-idp/backstage-plugins pull request #2339
Opened 2024-10-10 12:41 UTC by debsmita1

**Resolves:**
https://issues.redhat.com/browse/RHIDP-4035

2024-10-30 06:15 UTC, its-mitesh-kumar commented
@debsmita1 Could you please resolve quality gate failing and merge the latest change from main .

2024-11-04 11:42 UTC, christoph-jerolimov requested changes
Hi, from the user perspective I see two issues:

1. When I paginate between the pages, I always see a loading indicator.
2. The order by feature works just on the current page. I expect that this issue exists before, but server-side pagination works only when the server also supports server-side ordering.

2024-11-04 11:42 UTC, christoph-jerolimov commented on plugins/bulk-import/src/components/AddRepositories/AddRepositoriesForm.test.tsx
> +            <AddRepositories error={null} />
I see that it's already before like this, but can you make the `error` prop optional and remove the prop here?

2024-11-04 11:42 UTC, christoph-jerolimov commented on plugins/bulk-import/src/components/AddRepositories/AddRepositoriesForm.tsx
> +  } | null>(null);
You can use the error from the useMutation instead.

```suggestion
```

2024-11-04 11:42 UTC, christoph-jerolimov commented on plugins/bulk-import/src/components/AddRepositories/AddRepositoriesForm.tsx
> +  });
I think it's easier if you handle this later by using the mutationCreate.error

```suggestion
  const mutationCreate = useMutation(createImportJobs);
```

2024-11-04 11:42 UTC, christoph-jerolimov commented on plugins/bulk-import/src/components/AddRepositories/AddRepositoriesForm.tsx
> +        <AddRepositories error={generalSubmitError} />
Maybe you can pass just `mutationCreate.error` here. Or you can convert after `const mutationCreate` with

```tsx
  const generalSubmitError = mutationCreaten.errro ? ({
    message:
      error?.message ||
        `${get(error, 'error.message')}\n${get(error, 'error.response.url')}` ||
        'Failed to create pull request',
    title: error?.name || get(error, 'error.name') || 'Error occured',
  }) : null;
```

```suggestion
        <AddRepositories error={generalSubmitError} />
```

Wdyt?

2024-11-04 11:42 UTC, christoph-jerolimov commented on plugins/bulk-import/src/hooks/useRepositories.test.ts
> +      error: '',
I would expect error is null when there is no error.

```suggestion
      error: null,
```

2024-11-04 11:42 UTC, christoph-jerolimov commented on plugins/bulk-import/src/hooks/useRepositories.test.ts
> +      error: '',
```suggestion
      error: null,
```

2024-11-04 11:42 UTC, christoph-jerolimov commented on plugins/bulk-import/src/hooks/useRepositories.test.ts
> +      error: '',
```suggestion
      error: null,
```

2024-11-04 11:42 UTC, christoph-jerolimov commented on plugins/bulk-import/src/hooks/useRepositories.ts
>    return useDeepCompareMemoize({
I see an issue that the pagination forward and backend shows always a loading indicator.

I guess that the `useRepository` doesn't use the caching benefits of react-query yet/correctly.

My recommendation is that you remove almost all useStates from this hook.

If you need calculate results, based on the useQuery hook, you can use `useMemo` instead.

The code should also get rid off the effect to call debouncedUpdateResources and the deepCompareMemoize function.

The order should be:

1. useQuery to fetch data
2. useMemo if you must transform "complex" data with a dependency just on the data.

2024-11-05 16:52 UTC, debsmita1 commented
Created PR https://github.com/redhat-developer/rhdh-plugins/pull/23 , so closing this one

2024-11-05 16:52 UTC, closed without merging