feat(k8s-actions): Add create namespace action
janus-idp/backstage-plugins pull request #292
Opened 2023-04-25 11:37 UTC by SamoKopecky

Resolves #175 

- Add a new package for kubernetes actions with version `v1.0.0` and set it to public
- Add a custom scaffolder action to create a Kubernetes repository using the kubernetes client API library
- Add documentation for the created action
- Add tests for the created action

The `name` parameter that is used in the kube config values (like `cluster`, `name` ...) can be anything as far as I am aware since I think its only used for the kube config description itself and not for the API calls. 

Note: Checks for required parameters are not done in code since they part of the schema and backstage won't run the actions unless it has all of the required parameters.

2023-04-25 12:00 UTC, tumido requested changes
For a technical nit, see inline.

On a different topic:

I don't think we should expect the user to know the target cluster API URL or understand what is the local cluster. Instead, we should:
1. Either be able to consume this data from the Backstage Catalog (we can safely assume all clusters are stored as `kind: Resource` with `spec.type: kubernetes-cluster`) and offer those as a dropdown in the scaffolder form as entity references. The action should recognize it and pull the appropriate API URL annotation from the catalog.
2. Additionally we can provide value for *Other* which would conditionally allow the user to specify the API URL directly.


I know most of the above is handled on the Template side and not within the action itself, however, I think we should provide means to support these usecases - currently, it would be really challenging without changes in the action itself.

WDYT?

Additionally, I don't think you should provide `localCluster` flag since the user typically has no understanding of that (if Backstage is deployed on Kubernetes at all).

2023-04-25 12:35 UTC, SamoKopecky commented
> For a technical nit, see inline.
> 
> On a different topic:
> 
> I don't think we should expect the user to know the target cluster API URL or understand what is the local cluster. Instead, we should:
> 
>     1. Either be able to consume this data from the Backstage Catalog (we can safely assume all clusters are stored as `kind: Resource` with `spec.type: kubernetes-cluster`) and offer those as a dropdown in the scaffolder form as entity references. The action should recognize it and pull the appropriate API URL annotation from the catalog.
> 
>     2. Additionally we can provide value for _Other_ which would conditionally allow the user to specify the API URL directly.
> 
> 
> I know most of the above is handled on the Template side and not within the action itself, however, I think we should provide means to support these usecases - currently, it would be really challenging without changes in the action itself.
> 
> WDYT?
> 
> Additionally, I don't think you should provide `localCluster` flag since the user typically has no understanding of that (if Backstage is deployed on Kubernetes at all).

I think that's a great idea and much user friendly then the current solution. I'll update the action.

2023-04-28 17:06 UTC, SamoKopecky commented on plugins/kubernetes-actions/package.json
> +  ]
Resoled in the latest commit.

2023-04-28 17:07 UTC, SamoKopecky commented
The action now supports either using a catalog cluster of an API url.

2023-05-11 13:16 UTC, tumido requested changes

2023-05-11 13:16 UTC, tumido commented on plugins/kubernetes-actions/src/actions/createKubernetesNamespace.ts
> +          namespaceName: {
can we rename this to `namespace` please?

2023-05-11 13:16 UTC, tumido commented on plugins/kubernetes-actions/src/actions/createKubernetesNamespace.ts
> +        required: ['namespaceName', 'token'],
Should also contain `oneOf`:
https://json-schema.org/understanding-json-schema/reference/combining.html?highlight=oneof#oneof

```
oneOf: [{required: ['url']}, {required: ['clusterRef']} ]
```

2023-05-12 07:52 UTC, SamoKopecky commented
Thanks for the feedback, changes applied in the latest commits.

2023-05-31 13:14 UTC, tumido requested changes
A little nit for the README. Otherwise LGTM

2023-05-31 13:14 UTC, tumido commented on plugins/kubernetes-actions/README.md
> +     namespaceName: foo
Please update to reflect the previously discussed changes.

2023-05-31 14:39 UTC, merged