Build new backstage plugin for Azure Container Registry
janus-idp/backstage-plugins pull request #313
Opened 2023-04-28 18:18 UTC by yzhao583

Story: [https://github.com/janus-idp/backstage-plugins/issues/216](https://github.com/janus-idp/backstage-plugins/issues/216)

Functionality:
- Fetch and display tags information for a [repository](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-concepts) from Azure Container Registry.

Screenshot:
![Screenshot 2023-04-28 at 1 27 11 PM](https://user-images.githubusercontent.com/24922241/235223590-4c85cbc1-64e5-41a5-86bf-0753c41cceb5.png)

2023-05-02 09:06 UTC, tumido requested changes
Hey! Great start! Please mind we won't be able to do a proper technical review on a new plugin this week (due to our other commitments and deadlines). I've pointed out a few main details that have to be changed in the `package.json`. I'll try to get back to you with a proper technical review as soon as possible.

2023-05-02 09:06 UTC, tumido commented on plugins/acr/package.json
> +  "name": "@janus-idp/plugin-acr",
```suggestion
  "name": "@janus-idp/backstage-plugin-acr",
```

2023-05-02 09:06 UTC, tumido commented on plugins/acr/package.json
> +  "private": true,
```suggestion
```

2023-06-30 08:48 UTC, invincibleJai commented
closing this in favour of https://github.com/janus-idp/backstage-plugins/pull/483

2023-06-30 08:48 UTC, closed without merging