[WIP] Kiali plugin
janus-idp/backstage-plugins pull request #371
Opened 2023-05-18 13:48 UTC by aljesusg

- Plugins
  -  Kiali
  -  Kiali-Common
  -  Kiali-Backend 

# Demo

![image](https://github.com/janus-idp/backstage-plugins/assets/3019213/54df5009-209f-401e-a2e7-bea75c3ef3a1)

2023-07-18 15:44 UTC, tumido submitted a review, later dismissed
I've just briefly skimmed this for any major flaws and I haven't tested this. So far it looks good. I have found just a few minor issues we need to address. 👍

2023-07-18 15:44 UTC, tumido commented on plugins/kiali-common/src/helpers/config.ts
> +const KIALI_PREFIX = 'catalog.providers.kiali';
Please provide a config schema. You can see how we do it in other backend plugins:

https://github.com/janus-idp/backstage-plugins/blob/main/plugins/ocm-backend/config.d.ts

https://backstage.io/docs/conf/defining/

2023-07-18 15:44 UTC, tumido commented on plugins/kiali/package.json
> +  "private": true,
```suggestion
```

2023-07-20 00:15 UTC, tumido requested changes

2023-07-20 00:15 UTC, tumido commented on plugins/kiali-backend/package.json
> +    "dist"
please add `config.d.ts` to the dist here and also as:

```json
  "configSchema": "config.d.ts",
```

2023-07-20 12:26 UTC, aljesusg reviewed
Changes done

2023-07-20 14:08 UTC, tumido approved these changes
/lgtm
/approve

2023-07-20 14:10 UTC, aljesusg commented
> /lgtm
> 
> /approve

Hooray!

2023-07-20 15:38 UTC, jasperchui commented
resolves #552

2023-07-20 15:39 UTC, aljesusg commented
> resolves #552

Sorry, infact this resolves https://github.com/janus-idp/backstage-plugins/issues/248

2023-07-21 13:25 UTC, aljesusg commented
Sorry bu we are new in janus. Do we need to do anything else to merge this?

2023-07-25 10:32 UTC, tumido commented
No need to do anything. We had release tooling issues. It should be resolved now. 🙂 Merging. 👍

2023-07-25 10:32 UTC, tumido approved these changes
/lgtm
/approve

2023-07-25 10:32 UTC, merged

2023-07-25 10:33 UTC, aljesusg commented
Great thanks @tumido We did the documentation PR https://github.com/janus-idp/janus-idp.github.io/pull/183 !!!