docs(topology): Fixes to topology README
janus-idp/backstage-plugins pull request #468
Opened 2023-06-16 12:18 UTC by hmanwani-rh

GitHub issue: https://github.com/janus-idp/backstage-plugins/issues/393

JIRA: https://issues.redhat.com/browse/RHIDP-127

2023-06-19 10:27 UTC, invincibleJai approved these changes

2023-06-19 10:27 UTC, invincibleJai commented
@hmanwani-rh Semantic release job is not happy

2023-06-19 12:58 UTC, invincibleJai requested changes
change commit message as the semantic job is failing, change commit message to

```
docs(topology): fixes to topology README
```

check error `Please ensure that the subject
  doesn't start with an uppercase character.`

2023-06-20 09:04 UTC, hmanwani-rh commented
> change commit message as the semantic job is failing, change commit message to
> 
> ```
> docs(topology): fixes to topology README
> ```
> 
> check error `Please ensure that the subject doesn't start with an uppercase character.`

Done, thank you @invincibleJai

2023-06-21 09:41 UTC, merged