feat(acr): azure container registry plugin
janus-idp/backstage-plugins pull request #483
Opened 2023-06-22 15:40 UTC by invincibleJai

**Tracks:** https://github.com/janus-idp/backstage-plugins/issues/216

This is based on https://github.com/janus-idp/backstage-plugins/pull/313

**Description:** Azure container registry plugin allows Backstage users to view details of an image related to a catalog resource deployed from your Azure Container Registry.

**Screenshots/Gif:**

Light Theme:
<img width="1791" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/c305b7cc-b43b-4e44-9ff2-8224b5d0f22f">

Dark Theme:
<img width="1792" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/e7ee2bdc-788d-4a50-8b11-b3730e672989">

API Failure: 
<img width="1792" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/88a86397-4ed4-4301-8947-b282dae14309">

**Tests:**
<img width="994" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/7b29d441-ef1d-423c-9ebe-4b54f69f5d1f">

**TODO:**

- [x] Handle open review comments on https://github.com/janus-idp/backstage-plugins/pull/313
- [x] Refactor code and clean up
- [x] Error handling
- [x] Add Dev Setup
- [x] Add Tests

2023-07-04 18:37 UTC, debsmita1 commented on plugins/acr/dev/index.tsx
> +    title: 'Root Page',
update the title

2023-07-04 18:37 UTC, debsmita1 commented
The registry should be a link
acr
<img width="1717" alt="Screenshot 2023-07-05 at 12 04 30 AM" src="https://github.com/janus-idp/backstage-plugins/assets/22490998/9c055ecf-608c-4ec5-8176-c70178e92c67">

quay
<img width="1717" alt="Screenshot 2023-07-05 at 12 04 13 AM" src="https://github.com/janus-idp/backstage-plugins/assets/22490998/388ec225-1354-4b77-8092-ccb71fcc04ed">

2023-07-05 03:07 UTC, invincibleJai commented
> The registry repo should be a link acr <img alt="Screenshot 2023-07-05 at 12 04 30 AM" width="1717" src="https://user-images.githubusercontent.com/22490998/250972274-9c055ecf-608c-4ec5-8176-c70178e92c67.png">
> 
> quay <img alt="Screenshot 2023-07-05 at 12 04 13 AM" width="1717" src="https://user-images.githubusercontent.com/22490998/250972297-388ec225-1354-4b77-8092-ccb71fcc04ed.png">

am not sure why they kept in dev mode but in actual it is not, check below

<img width="1792" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/5d30b612-c8e2-4367-805d-7f00075ecdeb">

2023-07-12 18:13 UTC, debsmita1 commented
The sort on the manifest column is not working. Try using the column `render` instead of modifying the Table data.

2023-07-13 08:40 UTC, divyanshiGupta requested changes

2023-07-13 08:40 UTC, divyanshiGupta commented on plugins/acr/src/components/AzureContainerRegistry/AzureContainerRegistry.tsx
> +export const AzureContainerRegistry = ({ image }: { image: string }) => {
nit:
Can you create separate type for component props?

2023-07-13 10:27 UTC, tumido approved these changes
/lgtm
/approve

2023-07-13 10:28 UTC, tumido commented
The SonarCloud quality gate can be solved later with the slow refactoring of shared components into `@janus-idp/shared-react`. This can be a separate task.

2023-07-13 10:33 UTC, tumido approved these changes

2023-07-13 10:50 UTC, merged