feat(shared-react): update shared plugin
janus-idp/backstage-plugins pull request #532
Opened 2023-07-18 18:01 UTC by debsmita1

2023-07-19 09:55 UTC, invincibleJai commented
@debsmita1 Thanks for PR, pls link ticket to this

2023-07-20 05:33 UTC, invincibleJai commented on plugins/shared-react/src/components/pipeline/HorizontalStackedBars.tsx
> +  }
can't we add onClick directly on div?

2023-07-21 10:05 UTC, divyanshiGupta requested changes

2023-07-21 10:05 UTC, divyanshiGupta commented on plugins/shared-react/src/components/pipeline/HorizontalStackedBars.tsx
> +}) => (
@debsmita1 please create a type with these props.

2023-07-21 10:37 UTC, divyanshiGupta approved these changes
LGTM!

2023-07-21 10:39 UTC, merged