docs(topology): update README.md
janus-idp/backstage-plugins pull request #678
Opened 2023-08-25 14:32 UTC by Zaperex

Fixes #677

2023-08-25 14:34 UTC, Zaperex commented
Should we include the list in the README at all? If so, should we have a separate file for the list when we add more icons?

The main reasoning for this list is just because I wasn't sure why certain types were not loading icons, and didn't know what runtime types would load one.

2023-08-28 11:47 UTC, divyanshiGupta commented
cc: @hmanwani-rh

2023-08-29 09:49 UTC, hmanwani-rh requested changes
@Zaperex Added a couple of suggestions, the rest looks good.

2023-08-29 09:49 UTC, hmanwani-rh commented on plugins/topology/README.md
> +  Currently supported values of `<RUNTIME_NAME>`:
```suggestion
  Supported values of `<RUNTIME_NAME>` include:
```

2023-08-29 09:49 UTC, hmanwani-rh commented on plugins/topology/README.md
> +  Any other values would result in no icons being rendered for the node.
```suggestion
Other values result in icons not being rendered for the node. 
 
```

2023-08-29 13:40 UTC, divyanshiGupta commented
@Zaperex the PR is not adding any new packages or updating any versions so lets not update `yarn.lock`.

2023-08-29 13:46 UTC, Zaperex commented
ah I didn't realize it updated the yarn.lock, I'll fix that

2023-08-29 14:22 UTC, hmanwani-rh approved these changes

2023-08-29 14:30 UTC, merged