chore(deps): upgrade Patternfly to version 5
janus-idp/backstage-plugins pull request #715
Opened 2023-09-06 12:17 UTC by jeff-phillips-18

Fixes: https://github.com/janus-idp/backstage-plugins/issues/648

/cc @invincibleJai

2023-09-06 12:28 UTC, tumido requested changes

2023-09-06 12:28 UTC, tumido commented on plugins/ocm/package.json
> +    "@patternfly/react-icons": "5.0.0",
Can we please allow `^` caret versions? (in all packages)

2023-09-06 12:34 UTC, tumido commented on plugins/topology/src/common/components/icons.tsx
Note: Thanks to SonarCloud this led me to discover we need to reopen https://github.com/janus-idp/backstage-plugins/issues/582

cc @divyanshiGupta

2023-09-06 12:58 UTC, divyanshiGupta commented on plugins/topology/src/common/components/icons.tsx
@tumido icons was not moved to the shared-package because at the moment it was decided not to add a dependency on patternfly/react-icons and rather user MUI icons if possible and have a separate issue for refactoring icons to use MUI icons and update tekton and topology plugins based on that change. LMK wdyt.
cc: @invincibleJai

2023-09-06 13:08 UTC, tumido commented on plugins/topology/src/common/components/icons.tsx
Got it, thank you. I agree with that. 🙂 Do we have that refactoring tracked in an issue somewhere?

2023-09-06 17:49 UTC, jeff-phillips-18 commented on plugins/topology/src/components/Graph/decorators/EditDecorator.tsx
> +      <g data-id="============ DECORATOR ============" ref={decoratorRef}>
Heh, that was just a test that I forgot to remove.

2023-09-07 06:14 UTC, invincibleJai commented
Thanks @jeff-phillips-18. Some type errors are shown here on topology https://github.com/janus-idp/backstage-plugins/actions/runs/6101300353/job/16557365720?pr=715

2023-09-07 08:37 UTC, tumido approved these changes
Besides test failures I see no issues with this PR. 👍 

Please do not mind the SonarCloud Quality Gate failure, it's not meant to be fixed in this PR. 🙂

2023-09-08 07:16 UTC, invincibleJai approved these changes
Thanks @jeff-phillips-18, verified both topology and tekton plugin/

2023-09-08 07:21 UTC, invincibleJai commented
LGTM

2023-09-11 06:12 UTC, merged