docs(nexus): update nexus CONTRIBUTING.md and turbo to ensure generate command is ran
janus-idp/backstage-plugins pull request #718
Opened 2023-09-06 13:54 UTC by Zaperex

## Description

- Updates the nexus plugin `CONTRIBUTING.md` with both the turbo supported command as well as the regular `yarn workspace` command.
- Also updates the nexus plugin's `turbo.json` to ensure `generate` is always ran before a `start` when running `yarn start --filter=@janus-idp/backstage-nexus-repository-manager` from the root directory.

## What issue(s) does this fix?
Fixes #703

2023-09-06 16:21 UTC, schultzp2020 requested changes

2023-09-06 17:23 UTC, Zaperex commented on plugins/nexus-repository-manager/CONTRIBUTING.md
>  yarn workspace @janus-idp/backstage-plugin-nexus-repository-manager run start
@schultzp2020 The main reasoning is that the `yarn run start --filter=` command only works in the plugin directory itself, and Tom recommended to just use the workspace command. https://github.com/janus-idp/backstage-plugins/pull/705#discussion_r1317105186

2023-09-06 19:41 UTC, schultzp2020 approved these changes
LGTM

2023-09-07 08:38 UTC, tumido approved these changes
/lgtm
/approve

2023-09-07 08:38 UTC, merged