sort nexus artifacts by most recent first by default
janus-idp/backstage-plugins pull request #829
Opened 2023-10-06 22:08 UTC by mjhumkhawala-ias

In order to reduce clutter in the users view, when the artifact table is displayed, it should be sorted by most recent first. The nexus plugin by default does not do that. This pr updates the nexus api client call by including a sort parameter based on `version`.

Default - 
<img src= "https://github.com/janus-idp/backstage-plugins/assets/52285907/7ad5c348-7d7b-465c-8f03-14046d45c521" width=200 height=100></img><img src="https://github.com/janus-idp/backstage-plugins/assets/52285907/340c77d1-e21d-45ce-af61-26d30fc7678d" width=200 height=100 ></img>

After passing in the sort parameter
<img src="https://github.com/janus-idp/backstage-plugins/assets/52285907/f5ea1d1b-11d8-4aef-8769-6fdfd271e1ba" width=200 height=100 ></img><img width="200" height=100 alt="sorted_2" src="https://github.com/janus-idp/backstage-plugins/assets/52285907/9027a161-44b2-4528-844a-d243c3af8396">

2023-10-11 11:30 UTC, invincibleJai approved these changes
LGTM

2023-10-11 13:05 UTC, invincibleJai requested changes
test needs update https://github.com/janus-idp/backstage-plugins/actions/runs/6436912328/job/17600283351?pr=829

2023-10-11 15:02 UTC, mjhumkhawala-ias commented
> test needs update https://github.com/janus-idp/backstage-plugins/actions/runs/6436912328/job/17600283351?pr=829

Fixed useNexusRepositoryManagerAppData tests
results from local run - 
```
PASS  src/hooks/useNexusRepositoryManagerAppData.test.ts
  useNexusRepositoryManagerAppData
    ✓ should require annotations (461 ms)
    ✓ should require an entity with an annotation (36 ms)
    ✓ should return title and query (17 ms)
    ✓ should return title and query with multiple repositories (11 ms)
    ✓ should have a custom title (6 ms)
    
    Test Suites: 6 passed, 6 total
Tests:       23 passed, 23 total
Snapshots:   0 total
Time:        22.581 s
Ran all test suites.
```
could you please approve the build & test action - https://github.com/janus-idp/backstage-plugins/actions/runs/6484233164

2023-10-13 05:40 UTC, invincibleJai approved these changes
LGTM

2023-10-13 05:40 UTC, merged