WIP: Update Keycloack plugin for dynamic backend
janus-idp/backstage-plugins pull request #869
Opened 2023-10-23 21:21 UTC by craigtracey

Add dynamic backend module capabilities for the Keycloak backend plugin.

2023-10-25 14:42 UTC, tumido requested changes

2023-10-25 14:42 UTC, tumido commented on plugins/keycloak-backend/CHANGELOG.md
Can you please undo the CHANGELOG changes? 🙂

2023-10-25 14:42 UTC, tumido commented on plugins/keycloak-backend/package.json
Can you please also add the `export-dynamic` script, so we can actually export that dynamic package?

2023-10-25 14:42 UTC, tumido commented on plugins/keycloak-backend/package.json
> +    "role": "backend-plugin-module"
You are right about this! Correct! 🙂

2023-10-25 14:44 UTC, tumido commented
Thank you for your PR, @craigtracey ! 👍 I see only minor nits, nothing major 👍 🙂

2023-10-25 15:42 UTC, craigtracey commented on plugins/keycloak-backend/CHANGELOG.md
These were coming from failing Prettier tests. Will undo and see if it passes.

2023-10-25 17:26 UTC, craigtracey commented on plugins/keycloak-backend/package.json
As this is new, I am not familiar with it yet. Will take a look and attempt to incorporate it.

2023-10-26 13:21 UTC, davidfestal requested changes

2023-10-26 13:23 UTC, davidfestal commented on plugins/ocm/package.json
> +  "version": "3.3.0",
Why this change ?

2023-10-26 13:32 UTC, davidfestal requested changes
This PR has adds support for the Backstage new backend system.
However this is not sufficient to add support for the Dynamic backend plugins loading in the Janus Showcase applcation, since the Janus `backstage-showcase` is still based on the legacy backend system, until the new backend leaves the alpha state.
So for now you have to add some additional entrypoints that will provide dynamic loading logic for both the old and the new backend system.
The code to add in the Keycloak case can be found in the [dynamic folder of the corresponding showcase wrapper](https://github.com/janus-idp/backstage-showcase/tree/main/dynamic-plugins/wrappers/janus-idp-backstage-plugin-keycloak-backend-dynamic/src/dynamic)

2023-10-27 20:26 UTC, craigtracey commented on plugins/ocm/package.json
> +  "version": "3.3.0",
This was an artifact of a bad rebase.

2023-10-27 20:28 UTC, craigtracey commented on plugins/keycloak-backend/package.json
> +    "@dfatwork-pkgs/backstage-cli": "0.22.9-next.6",
Done

2023-10-27 20:28 UTC, craigtracey commented on plugins/keycloak-backend/package.json
> +    "export-dynamic": "backstage-cli package export-dynamic-plugin --embed-package @backstage/plugin-explore-backend --embed-package @backstage/plugin-search-backend-module-explore"
Done

2023-10-27 20:28 UTC, craigtracey commented on plugins/keycloak-backend/package.json
Added

2023-10-27 20:29 UTC, craigtracey commented on plugins/keycloak-backend/CHANGELOG.md
Reverted

2023-10-27 20:47 UTC, craigtracey commented
> This PR has adds support for the Backstage new backend system. However this is not sufficient to add support for the Dynamic backend plugins loading in the Janus Showcase applcation, since the Janus `backstage-showcase` is still based on the legacy backend system, until the new backend leaves the alpha state. So for now you have to add some additional entrypoints that will provide dynamic loading logic for both the old and the new backend system. The code to add in the Keycloak case can be found in the [dynamic folder of the corresponding showcase wrapper](https://github.com/janus-idp/backstage-showcase/tree/main/dynamic-plugins/wrappers/janus-idp-backstage-plugin-keycloak-backend-dynamic/src/dynamic)

I am not familiar with how Janus Showcase fits in here. As I look at Janus Showcase, it looks as if the keycloak backend has already been moved to the new backend system. Does that work make this PR obsolete?

2023-11-07 10:58 UTC, davidfestal commented
> > This PR has adds support for the Backstage new backend system. However this is not sufficient to add support for the Dynamic backend plugins loading in the Janus Showcase applcation, since the Janus `backstage-showcase` is still based on the legacy backend system, until the new backend leaves the alpha state. So for now you have to add some additional entrypoints that will provide dynamic loading logic for both the old and the new backend system. The code to add in the Keycloak case can be found in the [dynamic folder of the corresponding showcase wrapper](https://github.com/janus-idp/backstage-showcase/tree/main/dynamic-plugins/wrappers/janus-idp-backstage-plugin-keycloak-backend-dynamic/src/dynamic)
> 
> I am not familiar with how Janus Showcase fits in here. As I look at Janus Showcase, it looks as if the keycloak backend has already been moved to the new backend system. Does that work make this PR obsolete?

It doesn't make this PR at all.
Dynamic plugins in the Janus Showcase has been designed to support both the old backend system and the new backend system (at least until the new backend system is completely out of alpha status).
This is why There are some additions required on top of what you already provided.
But this would be part of a followup PR that would complement this one.

Let's merge your PR already.

2023-11-07 13:32 UTC, davidfestal approved these changes

2023-11-07 13:55 UTC, merged